packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@hono/node-server": ^2.0.0
  "@types/node": ^25.6.0
  hono: 4.12.15
  tsx: ^4.21.0
  typescript: ^6.0.3

onlyBuiltDependencies:
  - esbuild
  - msw
  - sharp
  - unrs-resolver
