name: Verification

on:
  push:
    branches:
      - "**"

jobs:
  typecheck:
    name: Typecheck

    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install Packages
        run: pnpm install --frozen-lockfile

      - name: Run Command
        run: pnpm check:types

  format-and-lint:
    name: Format & Lint

    runs-on: blacksmith-4vcpu-ubuntu-2404

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install Packages
        run: pnpm install --frozen-lockfile

      - name: Run Command
        run: pnpm check:style
