name: Manage Deployments

on:
  push:
    branches-ignore:
      - "main"

  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to promote."
        required: false
        type: string

      commit:
        description: "The commit to promote."
        required: false
        type: string

jobs:
  deploy-and-promote-preview:
    name: Deploy & Promote Preview

    runs-on: blacksmith-4vcpu-ubuntu-2404

    env:
      SHARED_PROVIDER_GITHUB_REPOSITORY_ID: ${{ vars.SHARED_PROVIDER_GITHUB_REPOSITORY_ID }}
      SHARED_PROVIDER_GITHUB_SECRET: ${{ secrets.SHARED_PROVIDER_GITHUB_SECRET }}

      SHARED_PROVIDER_VERCEL_TEAM_ID: ${{ vars.SHARED_PROVIDER_VERCEL_TEAM_ID }}
      SHARED_PROVIDER_VERCEL_SECRET: ${{ secrets.SHARED_PROVIDER_VERCEL_SECRET }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create and promote preview deployments from workflow dispatch

        if: github.event_name == 'workflow_dispatch'
        run: pnpm preview:promote -- --branch "${{ inputs.branch }}" --commit "${{ inputs.commit }}"

      - name: Create and promote preview deployments from push

        if: github.event_name == 'push'
        run: pnpm preview:promote
