name: Deployment

on:
  push:
    branches-ignore:
      - "main"

jobs:
  preview:
    name: Preview

    runs-on: blacksmith-4vcpu-ubuntu-2404

    env:
      SHARED_PROVIDER_GITHUB_REPOSITORY_ID: ${{ vars.SHARED_PROVIDER_GITHUB_REPOSITORY_ID }}
      SHARED_PROVIDER_GITHUB_SECRET: ${{ secrets.SHARED_PROVIDER_GITHUB_SECRET }}

      SHARED_PROVIDER_VERCEL_TEAM_ID: ${{ vars.SHARED_PROVIDER_VERCEL_TEAM_ID }}
      SHARED_PROVIDER_VERCEL_SECRET: ${{ secrets.SHARED_PROVIDER_VERCEL_SECRET }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install Packages
        run: pnpm install --frozen-lockfile

      - name: Run Command
        run: pnpm preview:promote -- --branch "${{ github.ref_name }}"
